name: spotistas

services:
  api:
    image: node:18.14.0-alpine3.17
    ports:
      - 5000:5000
    user: node
    working_dir: /api
    command: /bin/sh /api/.docker.sh
    volumes:
      - .:/api
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    links:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "exit 0"

volumes:
  postgres:

networks:
  default:
