version: "3"

services:
  postgres:
    container_name: spotistas-db
    image: postgres:15-alpine
    restart: unless-stopped
    hostname: postgres
    networks:
      - spotistas
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    healthcheck:
      test: "exit 0"

volumes:
  postgres:
   name: spotistas-db

networks:
  spotistas:
    name: spotistas
