version: "3"

services:
  api:
    container_name: spotistas-api
    image: node:18.14.0-alpine
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run prisma && npm start"
    networks:
      - spotistas
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${PORT}/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    container_name: spotistas-db
    image: postgres:15-alpine
    restart: unless-stopped
    hostname: postgres
    networks:
      - spotistas
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    healthcheck:
      test: "exit 0"

volumes:
  postgres:
   name: spotistas-db

networks:
  spotistas:
    name: spotistas
